name: Combined CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  e2e_test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Start Server
        run: |
          npm run start-prod &
          echo "Server started in the background"
      - name: Run Cypress E2E Tests (Headless)
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e:headless
          wait-on: http://localhost:5000
          wait-on-timeout: 30

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Build for production
        run: npm run build
      - name: Deploy to Render
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"