name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World! Hola mundo"
  date_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Now it is
        run: |
          date -u
  directory_content_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Directory content
        run: |
          ls -l
  cypress_job:
    runs-on: ubuntu-20.04
    steps:
    - name: e2e tests
      uses: cypress-io/github-action@v5
      with:
        command: npm run test:e2e
        start: npm run start-prod
        wait-on: http://localhost:5000